version: "3.8"

services:
  elasticsearch:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "127.0.0.1:9200:9200"
    volumes:
      - /data/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - elk_network

  kibana:
    build:
      context: ./kibana
      dockerfile: Dockerfile
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - server.publicBaseUrl=https://kibana.shopme.blog
    networks:
      - elk_network
    depends_on:
      - elasticsearch

  logstash:
    build:
      context: ./logstash
      dockerfile: Dockerfile
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    networks:
      - elk_network
    depends_on:
      - elasticsearch

  filebeat:
    build:
      context: ./filebeat
      dockerfile: Dockerfile
    user: root
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    depends_on:
      - logstash
    networks:
      - elk_network

  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-admin}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    networks:
      - elk_network

networks:
  elk_network:
    driver: bridge
